In [20]:
import pandas as pd


In [21]:
import pandas as pd
newdf=pd.read_csv("../datas/Medicaldataset.csv")

In [22]:
newdf.head

<bound method NDFrame.head of       Age  Gender  Heart rate  Systolic blood pressure  \
0      64       1          66                      160   
1      21       1          94                       98   
2      55       1          64                      160   
3      64       1          70                      120   
4      55       1          64                      112   
...   ...     ...         ...                      ...   
1314   44       1          94                      122   
1315   66       1          84                      125   
1316   45       1          85                      168   
1317   54       1          58                      117   
1318   51       1          94                      157   

      Diastolic blood pressure  Blood sugar  CK-MB  Troponin    Result  
0                           83        160.0   1.80     0.012  negative  
1                           46        296.0   6.75     1.060  positive  
2                           77        270.0   1.99    

In [23]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Age                       1319 non-null   int64  
 1   Gender                    1319 non-null   int64  
 2   Heart rate                1319 non-null   int64  
 3   Systolic blood pressure   1319 non-null   int64  
 4   Diastolic blood pressure  1319 non-null   int64  
 5   Blood sugar               1319 non-null   float64
 6   CK-MB                     1319 non-null   float64
 7   Troponin                  1319 non-null   float64
 8   Result                    1319 non-null   object 
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB


In [24]:
result=pd.get_dummies(data=newdf,columns=['Result'],drop_first=True,dtype='int64')

In [25]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()

In [26]:
result=newdf['Result']

In [27]:
Result=lab.fit_transform(result)

In [28]:
Result

array([0, 1, 0, ..., 1, 1, 1])

In [29]:
newdf.pop('Result')

0       negative
1       positive
2       negative
3       positive
4       negative
          ...   
1314    negative
1315    positive
1316    positive
1317    positive
1318    positive
Name: Result, Length: 1319, dtype: object

In [30]:
newdf['Result']=Result

In [31]:
newdf['Result'].value_counts()

Result
1    810
0    509
Name: count, dtype: int64

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
lr=RandomForestClassifier()
from sklearn.model_selection import train_test_split
y=newdf.pop('Result') 
x_train,x_test,y_train,y_test=train_test_split(newdf,y)

In [33]:
lr.fit(x_train,y_train)

RandomForestClassifier()

In [34]:
from sklearn.metrics import accuracy_score,confusion_matrix
pred=lr.predict(x_test)
acc=accuracy_score(y_test,pred)
conf=confusion_matrix(y_test,pred)

In [35]:
acc

0.990909090909091

In [36]:
conf

array([[124,   2],
       [  1, 203]], dtype=int64)

In [37]:
# import joblib
# joblib.dump(lr,"perfectmodel.joblib")

In [38]:
newdf

Age  Gender  Heart rate  Systolic blood pressure  \
0      64       1          66                      160   
1      21       1          94                       98   
2      55       1          64                      160   
3      64       1          70                      120   
4      55       1          64                      112   
...   ...     ...         ...                      ...   
1314   44       1          94                      122   
1315   66       1          84                      125   
1316   45       1          85                      168   
1317   54       1          58                      117   
1318   51       1          94                      157   

      Diastolic blood pressure  Blood sugar  CK-MB  Troponin  
0                           83        160.0   1.80     0.012  
1                           46        296.0   6.75     1.060  
2                           77        270.0   1.99     0.003  
3                           55        270.0  13.87     0.122  
4                           65        300.0   1.08     0.003  
...                        ...          ...    ...       ...  
1314                        67        204.0   1.63     0.006  
1315                        55        149.0   1.33     0.172  
1316                       104         96.0   1.24     4.250  
1317                        68        443.0   5.80     0.359  
1318                        79        134.0  50.89     1.770  

[1319 rows x 8 columns]

In [39]:
newdf.columns

Index(['Age', 'Gender', 'Heart rate', 'Systolic blood pressure',
       'Diastolic blood pressure', 'Blood sugar', 'CK-MB', 'Troponin'],
      dtype='object')

In [40]:
new=[65, 1, 110, 190, 125, 250, 10, 0.08]

In [57]:
import numpy as np
finaltesting=np.array(new).reshape(1,-1)

In [58]:
finaltesting=pd.DataFrame(finaltesting,columns=newdf.columns)

0     65.00
1      1.00
2    110.00
3    190.00
4    125.00
5    250.00
6     10.00
7      0.08
dtype: float64

In [61]:
testt=lr.predict(finaltesting)

In [62]:
testt

array([1])

In [55]:
newdf.shape

(1319, 8)

In [60]:
finaltesting

Age  Gender  Heart rate  Systolic blood pressure  \
0  65.0     1.0       110.0                    190.0   

   Diastolic blood pressure  Blood sugar  CK-MB  Troponin  
0                     125.0        250.0   10.0      0.08

In [63]:
import joblib
joblib.dump(lr,"finalfinalmodel.joblib")

['finalfinalmodel.joblib']